backend:
  name: github
  repo: imhaikun/blog
  branch: main
  base_url: https://one.202616.xyz
  auth_type: personal_token

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}
