local_backend: true

backend:
  name: github
  repo: imhaikun/blog
  branch: main
  base_url: https://one.202616.xyz
  auth_endpoint: api/auth

media_folder: "source/images"
public_folder: "/images"
media_library:
  name: "r2"
  config:
    upload_url: "/api/r2-upload"
    base_url: "https://images.202616.xyz"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    summary: '{{title}} · {{date | date("YYYY-MM-DD")}}'
    sortable_fields: ['date', 'title']
    view_filters:
      - label: "按年份"
        field: date
        pattern: ""
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "作者", name: "author", widget: "string", required: false}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "分类", name: "categories", widget: "string", required: false}
      - {label: "标签", name: "tags", widget: "list", field: {label: "标签", name: "tag", widget: "string"}, required: false}
      - {label: "正文", name: "body", widget: "markdown"}
